### ISSUE TITLE
Modification setPosPlayer

### ISSUE THREAD

**Issue by chirom2** [e-Gotcha/Struts#4]
@Lautre3091 
Il faudrait modifier cette accès api.
Il faut un truc du type:
{
    "pseudo" : "<pseudo>",
    "password" : "<password>",
    "idGame" : "<idGame>",
    "latitude" : "<latiude>"
    "longitude": "<longitude>"
}

Merci d'avance

**Comment by jgoas** [comment]
Gweltaz, tu n'as pas push l'intégration de mercredi. Je t'envoi par mail le fichier à intégrer.
Donc soit tu met à jour le git et j'intègre ce que demande Romain, soit je te laisse le faire :)
Préviens moi :)

**Comment by Lautre3091** [comment]
Je m'en occupe tout de suite


Le 3 avril 2015 21:47, jgoas <notifications@github.com> a écrit :

> Gweltaz, tu n'as pas push l'intégration de mercredi. Je t'envoi par mail
> le fichier à intégrer.
> Donc soit tu met à jour le git et j'intègre ce que demande Romain, soit je
> te laisse le faire :)
> Préviens moi :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-Gotcha/Struts/issues/4#issuecomment-89405163>.
>



-- 
Gweltaz GESTIN

**Comment by jgoas** [comment]
Merci, si tu peux mettre à jour en plus sur le serveur, ce sera parfait :)

Tu gères merci :)

**Comment by Lautre3091** [comment]
That will be done in 10 minutes bro :P

2015-04-03 21:52 GMT+02:00 jgoas <notifications@github.com>:

> Merci, si tu peux mettre à jour en plus sur le serveur, ce sera parfait :)
>
> Tu gères merci :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/e-Gotcha/Struts/issues/4#issuecomment-89405866>.
>



-- 
Gweltaz GESTIN

**Comment by jgoas** [comment]
Nice bro :)
